### PR TITLE
feat: Preserve HTML data attributes (from spans to anchors)

### LINKED ISSUE #41: feature: Keep data-attributes of spans
### Is your feature request related to a problem? Please describe.
I'd like to take advantage of mkdocs-material's instant previews, by adding `data-preview` to autorefs spans generated by mkdocstrings-python. Unfortunately, autorefs matches spans with a regex, and this regex is strict and only matches spans with exactly one `data-autorefs-*` attribute.

### Describe the solution you'd like
I'd like autorefs to allow other data- attributes to appear in its spans, and report them to anchors when it transforms them.

### Describe alternatives you've considered
/

### Additional context
https://github.com/squidfunk/mkdocs-material/issues/6704

### PR DESCRIPTION
**Pull request by pawamoy**
Closes #41

(will squash to add you as co-author @oprypin)

### CODE REVIEW

**Comment by oprypin** [comment]
Could you explain to me, I actually don't know what kind of issues this would be. No, I didn't predict this. I only meant if you need to parse the attributes but apparently that's not even needed 🙂

**Comment by pawamoy** [comment]
Well, autorefs sets `class=...` on anchors, so if someone sets `class=...` on an autorefs span, anchors will end up with two class attributes. Maybe browsers don't mind though?

**Comment by oprypin** [comment]
Ah yes for sure multiple `class` would be super bad

**Comment by oprypin** [comment]
The reason that is it's still ok to do this is because all usages should be programmatic and we can still have strict requirements on them

**Comment by oprypin** [comment]
Commit https://github.com/oprypin/mkdocs-autorefs/commit/10d76d359dd5aa24cf3d93831d7a3c07bba7704d works accordingly

**Comment by pawamoy** [comment]
> The reason that is it's still ok to do this is because all usages should be programmatic and we can still have strict requirements on them

I've personally written autoref spans manually on a few occurrences :smile: 
But yeah it's not documented so we can consider it's not public API.

I've pushed your commit on this branch, thanks!

**Pull request merged**
